feat: BasicPlayer
AxisCommunications/media-stream-player-js pull request #83
Opened 2020-11-13 21:21 UTC by lekoaf

Added the `BasicPlayer` component. This is an attempt to create the "bare minimum" component that you need to play a stream from an AXIS camera.

Refactored the code a bit so there would be less code duplication between `Player` and `BasicPlayer`. Also gave the user of the web component the choice between `basic` and `advanced` which of course refers to the `BasicPlayer` and `Player` respectively.

2020-11-27 16:34 UTC, barnomasoz requested changes

2020-12-04 14:52 UTC, lekoaf commented on lib/MediaStreamPlayer.tsx
> +    return this.getAttribute('variant') ?? 'advanced'
Sadly, this doesn't work.

2020-12-04 14:53 UTC, lekoaf commented on lib/Settings.tsx
> +import { Format } from './utils/common'
Fixed.

2020-12-04 14:56 UTC, lekoaf commented on lib/MediaStreamPlayer.tsx
> +    return this.getAttribute('variant') ?? 'advanced'
Sorry, it did work. :)

2020-12-08 07:40 UTC, barnomasoz approved these changes

2020-12-08 07:42 UTC, merged